### ISSUE TITLE
Césures sur mobile

### ISSUE THREAD

**Issue by hiwelo** [alsacreations/KNACSS#171]
Je viens de tomber sur cette déclaration : 
```less
// hyphens on small screens
@media (max-width: @small-screen) {
  /* you shall not pass */
  div,
  textarea,
  table,
  td,
  th,
  code,
  pre,
  samp {
    word-wrap: break-word;
    hyphens: auto;
  }
}
```

En français, même si la césure est gérée par le navigateur, elle est souvent mal réalisée par rapport aux règles de l'académie française.
Est-il possible mettre en place ces déclarations de manière conditionnelles ?
Via un appel de classe particulier par exemple ? :smile_cat:

**Comment by raphaelgoetter** [comment]
Je me note l'idée de côté.

Ceci dit, dans l'énorme majorité des cas, le problème principal à régler est le débordement des contenus... les règles typographiques ne viennent souvent qu'ensuite en guise de bonus.

Ne *pas* appliquer de word-wrap sur les petits écrans par défaut va avoir pour conséquence que tous les contenus risquent alors de déborder, et malheureusement peu de monde aura les compétences pour activer word-wrap "à la main" :/

A première vue, je privilégierais plutôt l'inverse : si cette règle imposée est gênante pour la typo, mieux vaut la commenter ou l'activer sur mesure.

**Comment by hiwelo** [comment]
Effectivement.
Cela devient flagrant dans certains projets quand la variable `@small-screen` est ajustée. 
Mais je suis d'accord sur la nécessité de ne pas avoir de débordement de contenu.

Le soucis est qu'il est compliqué de commenter du contenu au sein de Knacss, vu qu'il est souvent en mode _vendor_.
On pourrait le réfléchir dans l'autre sens dans ce cas, avec une classe qui permet de le retour en arrière sur la césure. Non ? :smile_cat:

**Comment by raphaelgoetter** [comment]
avec des `!important` partout alors ? :p

**Comment by hiwelo** [comment]
Je suis sûr qu'il existe une autre solution qui montre moins l'**!importance** de retirer les césures quand c'est mal géré :p

**Comment by raphaelgoetter** [comment]
Oui j'en suis sûr également, suffit de la trouver !

**Comment by raphaelgoetter** [comment]
Idée ? 
Avis sur le choix de nommage de la classe ?

```css
// use .no-wrapping to disallow word-wrapping on small screens
@media (max-width: @small-screen) {
  .no-wrapping {
    word-wrap: normal;
    hyphens: manual;
  }
}
```
