### ISSUE TITLE
Fallback Internet Explorer pour Flexbox

### ISSUE THREAD

**Issue by f4bien** [alsacreations/KNACSS#182]
Bonjour,

Y-a-t'il une raison pour laquelle il n'y a pas de fallbacks sur l'affichage flexbox?

```less
[class*="#{$kna-namespace}flex-container"] {
  display : flex;
  flex-wrap: wrap;
}
```

au lieu de

```less
[class*="#{$kna-namespace}flex-container"] {
  display: table;
  display : flex;
  flex-wrap: wrap;

  > * {
    display: table-cell;
  }
}
```

Par avance, merci.
