### ISSUE TITLE
margin-left: -$gutter et centrage

### ISSUE THREAD

**Issue by Alysko** [alsacreations/KNACSS#187]
Bonjour,

Pour quelle raison, dans la classe grid, les enfants ont une marge seulement à gauche et, de ce fait, le contenu grid se retrouve avec un margin: -$gutter ? Pourquoi ne pas égaliser ainsi : 

`[class*="#{$kna-namespace}grid-"] {
  margin-left: -$gutter / 2;
  margin-right: -$gutter / 2;
}
[class*="#{$kna-namespace}grid-"] > * {
  margin-left: $gutter / 2;
  margin-right: $gutter / 2;
}`

J'imagine que si ce n'est pas ainsi, c'est pour une bonne raison. Mais si je ne modifie pas comme ça, lorsque j'ajoute de la marge droite et gauche (pour que le conteneur grid ne soit pas collé aux bords), le conteneur est décentré (car mon margin-left va annuler le margin-left: -$gutter).

**Comment by raphaelgoetter** [comment]
Bonjour @Alysko 

Je comprends bien ta demande et je vois où tu veux en venir.

Mais si je suis bien ton raisonnement et ton idée de modification, cela ne changera rien au fait que si tu veux modifier les marges du conteneur, tu casseras l'ensemble. En gros, qu'il y en ait juste à gauche ou bien des deux côtés, elles sont nécessaires et on ne peut malheureusement pas trop les modifier :/

La solution idéale serait bien entendu de ne pas imposer de marges sur le conteneur.

J'ai bidouillé un truc qui me semble tenir la route, à grand renfort de `:nth-child()` , mais il faudrait faire des tests pour voir si cela ne pose pas d'autres problèmes ailleurs sur d'autres fonctionnalités.

Le code Sass pourrait ressembler à ça : 

```css
$number: 4;
$gutter: 2rem;

.grid-#{$number} {
  display: flex;
  flex-wrap: wrap;
}
.grid-#{$number} > * {
  width: calc((100% / #{$number}) - (#{$gutter} * #{$number - 1} / #{$number}));
}
.grid-#{$number} > *:not(:nth-child(#{$number}n+1)) {
  margin-left: $gutter;
}
```

Compilé, on obtiendrait ça : 

```css
.grid-4 {
  display: flex;
  flex-wrap: wrap;
}

.grid-4 > * {
  width: calc((100% / 4) - (2rem * 3 / 4));
}

.grid-4 > *:not(:nth-child(4n+1)) {
  margin-left: 2rem;
}
```

Démo : http://codepen.io/raphaelgoetter/pen/QNjEEL?editors=1100#

Les avantages que je vois : 
- pas de marges (négatives) imposées sur le conteneur général

Les points communs avec la technique actuelle : 
- marges imposées sur chaque enfant de la grille (du coup, pas possible de les modifier à la main si on en a besoin)

Les désavantages que je vois : 
- le poids du sélecteur qui applique la marge sur les enfants passe d'un simple élément à un poids de classe supplémentaire (donc plus compliqué à modifier ou maintenir)
