### ISSUE TITLE
Désactiver toute animation/transition quand l'utilisateur l'a demandé

### ISSUE THREAD

**Issue by PhilippeVay** [alsacreations/KNACSS#301]
Hello,

cette astuce aurait sa place dans KNACSS :

```css
@media (prefers-reduced-motion: reduce) {
  * {
    animation: none !important;
    transition: none !important;
  }
}
```

Cela permet sur [Safari et Firefox](https://caniuse.com/#feat=prefers-reduced-motion) à un utilisateur le souhaitant de ne pas subir d'animation ni de transition CSS, bon pour l'accessibilité. Cette astuce permet d'automatiser sans qu'un·e inté/dév ait besoin d'y penser à chaque fois ou d'avoir à créer une mixin qui ferait la même chose au cas par cas.

Source : https://twitter.com/scottjehl/status/1085600505299111936
Vu ou revu dans les réponses https://hugogiraudel.com/2018/03/19/implementing-a-reduced-motion-mode/ (coupler avec une variable CSS et _tl;dr_)

Références : [MDN](https://developer.mozilla.org/fr/docs/Web/CSS/@media/prefers-reduced-motion) et [CSS-tricks](https://css-tricks.com/introduction-reduced-motion-media-query/)
